# Generated by Django 4.2 on 2023-11-07 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.UUIDField()),
                ('sentimiento', models.CharField(default='NONE', max_length=10)),
                ('likes', models.IntegerField(default=0)),
                ('date', models.DateField()),
                ('comentario', models.CharField(default='[]', max_length=99999)),
                ('text', models.CharField(max_length=10000)),
            ],
        ),
    ]
